# Project information
site_name: DevOps Courses
site_description: Complete learning platform for DevOps, MLOps and AIOps Engineers
site_author: Vishal Sen
site_url: https://learning.vishal-connect.com

# Configuration
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle
#   logo: assets/logo.png
#   favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
    # Navigation
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.expand
    - navigation.indexes

    # Content
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.tooltips

    # Search
    - search.suggest
    - search.highlight
    - search.share

    # TOC
    - toc.follow

plugins:
  - tags
  # - git-revision-date-localized
#   - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      auto_append:
        - includes/mkdocs.md
        - includes/glossary.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde




extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com
    - icon: fontawesome/brands/github
      link: https://github.com/senvishal02
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/vishalsen-connect
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_css:
  - stylesheets/extra.css

# Copyright
copyright: Copyright © 2026 Vishal Sen

not_in_nav: |
  ./courses/**/*.md

nav:
  - Home:
    - index.md
#   - Linux:
#       - Overview: ./courses/linux/index.md
#       - Introduction:
#           - What is Linux: ./courses/linux/00-Introduction/01-What-is-Linux.md
#           - Linux Architecture: ./courses/linux/00-Introduction/02-Linux-Architecture.md
#           - Linux Distributions: ./courses/linux/00-Introduction/03-Linux-Distributions.md
#           - Installation Guide: ./courses/linux/00-Introduction/04-Installation-Guide.md

#       - File System:
#           - Filesystem Hierarchy: ./courses/linux/01-File-System/01-Filesystem-Hierarchy.md
#           - File & Directory Commands: ./courses/linux/01-File-System/02-File-Directory-Commands.md
#           - Viewing & Editing Files: ./courses/linux/01-File-System/03-File-Viewing-Editing.md

#       - Users & Groups:
#           - User Accounts: ./courses/linux/02-User-Group-Management/01-User-Accounts.md
#           - Group Management: ./courses/linux/02-User-Group-Management/02-Group-Management.md
#           - Password Policies: ./courses/linux/02-User-Group-Management/03-Password-Policies.md

#       - Permissions:
#           - Permission Model: ./courses/linux/03-Permissions/01-Permission-Model.md
#           - Special Permissions: ./courses/linux/03-Permissions/02-Special-Permissions.md
#           - ACL: ./courses/linux/03-Permissions/03-ACL.md

#       - Processes & Services:
#           - Process Management: ./courses/linux/04-Process-Service-Management/01-Process-Management.md
#           - Systemd Services: ./courses/linux/04-Process-Service-Management/02-Systemd-Services.md
#           - Boot Process: ./courses/linux/04-Process-Service-Management/03-Boot-Process.md

#       - Package Management:
#           - Package Tools: ./courses/linux/05-Package-Management/01-Package-Tools.md
#           - Repository Management: ./courses/linux/05-Package-Management/02-Repository-Management.md

#       - Storage:
#           - Disk Management: ./courses/linux/06-Storage-Management/01-Disk-Management.md
#           - Filesystems: ./courses/linux/06-Storage-Management/02-Filesystems.md
#           - LVM: ./courses/linux/06-Storage-Management/03-LVM.md
#           - RAID: ./courses/linux/06-Storage-Management/04-RAID.md

#       - Networking:
#           - Network Basics: ./courses/linux/07-Networking/01-Network-Basics.md
#           - Network Commands: ./courses/linux/07-Networking/02-Network-Commands.md
#           - Network Configuration: ./courses/linux/07-Networking/03-Network-Configuration.md

#       - SSH & Remote Access:
#           - SSH Configuration: ./courses/linux/08-SSH-Remote-Access/01-SSH-Configuration.md
#           - Secure SSH: ./courses/linux/08-SSH-Remote-Access/02-Secure-SSH.md
#           - SCP & Rsync: ./courses/linux/08-SSH-Remote-Access/03-SCP-RSYNC.md

#       - Web Server:
#           - Apache: ./courses/linux/09-Web-Server/01-Apache.md
#           - Nginx: ./courses/linux/09-Web-Server/02-Nginx.md
#           - SSL Setup: ./courses/linux/09-Web-Server/03-SSL-Setup.md

#       - Security:
#           - Firewall: ./courses/linux/10-Security/01-Firewall.md
#           - SELinux: ./courses/linux/10-Security/02-SELinux.md
#           - System Hardening: ./courses/linux/10-Security/03-System-Hardening.md

#       - Shell Scripting:
#           - Bash Basics: ./courses/linux/11-Shell-Scripting/01-Bash-Basics.md
#           - Control Statements: ./courses/linux/11-Shell-Scripting/02-Control-Statements.md
#           - Automation Scripts: ./courses/linux/11-Shell-Scripting/03-Automation-Scripts.md

#       - Logs & Monitoring:
#           - Log Files: ./courses/linux/12-Logs-Monitoring/01-Log-Files.md
#           - Monitoring Tools: ./courses/linux/12-Logs-Monitoring/02-Monitoring-Tools.md

#       - Backup & Recovery:
#           - Backup Tools: ./courses/linux/13-Backup-Recovery/01-Backup-Tools.md
#           - Disaster Recovery: ./courses/linux/13-Backup-Recovery/02-Disaster-Recovery.md

#       - Advanced Administration:
#           - Docker: ./courses/linux/14-Advanced-Administration/01-Docker.md
#           - Ansible: ./courses/linux/14-Advanced-Administration/02-Ansible.md
#           - Virtualization: ./courses/linux/14-Advanced-Administration/03-Virtualization.md
#           - Performance Tuning: ./courses/linux/14-Advanced-Administration/04-Performance-Tuning.md

#       - Projects:
#           - Production Web Server Setup: ./courses/linux/15-Projects/01-Production-Web-Server-Setup.md
#           - Secure SSH Server: ./courses/linux/15-Projects/02-Secure-SSH-Server.md
#           - LVM RAID Implementation: ./courses/linux/15-Projects/03-LVM-RAID-Implementation.md
#           - Automated Backup System: ./courses/linux/15-Projects/04-Automated-Backup-System.md
#   - Git/ Github: ./courses/git/index.md
#   - Web Servers: ./courses/webserver/index.md
#   - Docker: ./courses/docker/index.md
#   - Kubernetes:
#       - Overview: ./courses/kubernetes/index.md
#       - Setup:
#           - Install Tools: ./courses/kubernetes/00-SETUP/01-tools-install.md
#           - Kind Cluster: ./courses/kubernetes/00-SETUP/02-kind-cluster/create-cluster.sh
#           - Minikube Install: ./courses/kubernetes/00-SETUP/03-minikube-install/install.md

#       - Core Workloads:
#           - Pods: ./courses/kubernetes/01-CORE-WORKLOADS/01-pods/README.md
#           - ReplicaSets: ./courses/kubernetes/01-CORE-WORKLOADS/02-replicasets/replicaset.yaml
#           - Deployments: ./courses/kubernetes/01-CORE-WORKLOADS/03-deployments/README.md
#           - DaemonSets: ./courses/kubernetes/01-CORE-WORKLOADS/04-daemonsets/daemonset.yaml
#           - StatefulSets: ./courses/kubernetes/01-CORE-WORKLOADS/05-statefulsets/statefulset-mysql.yaml
#           - Jobs & CronJobs: ./courses/kubernetes/01-CORE-WORKLOADS/06-jobs-cronjobs/job.yaml

#       - Networking:
#           - Services: ./courses/kubernetes/02-NETWORKING/01-services/clusterip.yaml
#           - Ingress: ./courses/kubernetes/02-NETWORKING/02-ingress/nginx-install.md
#           - DNS Communication: ./courses/kubernetes/02-NETWORKING/03-dns-communication/pod-to-pod-communication.md
#           - Network Policies: ./courses/kubernetes/02-NETWORKING/04-network-policies/network-policy.yaml

#       - Storage:
#           - Volumes: ./courses/kubernetes/04-STORAGE/01-volumes/emptydir.yaml
#           - Persistent Volumes: ./courses/kubernetes/04-STORAGE/02-persistent-volumes/pv.yaml
#           - Dynamic Provisioning: ./courses/kubernetes/04-STORAGE/03-dynamic-provisioning/dynamic-pvc.yaml

#       - Observability:
#           - Monitoring: ./courses/kubernetes/07-OBSERVABILITY/01-monitoring/prometheus-install.md
#           - Logging: ./courses/kubernetes/07-OBSERVABILITY/02-logging-efk/elasticsearch.yaml
#           - Alerting: ./courses/kubernetes/07-OBSERVABILITY/03-alertmanager/alertmanager-config.yaml

#       - Security:
#           - Pod Security: ./courses/kubernetes/08-SECURITY/01-pod-security/psp-psa.md
#           - Network Security: ./courses/kubernetes/08-SECURITY/02-network-security/zero-trust-policy.yaml
#           - Secrets Management: ./courses/kubernetes/08-SECURITY/03-secrets-management/vault-integration.md

#       - GitOps:
#           - ArgoCD: ./courses/kubernetes/10-GITOPS/01-argocd/argocd-install.md

#       - Projects:
#           - Fullstack App: ./courses/kubernetes/14-PROJECTS/01-fullstack-app
#           - Microservices Observability: ./courses/kubernetes/14-PROJECTS/02-microservices-observability
#           - CI/CD GitOps Pipeline: ./courses/kubernetes/14-PROJECTS/03-cicd-gitops-pipeline
#           - MLOps Pipeline: ./courses/kubernetes/14-PROJECTS/04-mlops-pipeline

#   - Ansible: ./courses/ansible/index.md
#   - AWS: ./courses/aws/index.md
#   - Azure: ./courses/azure/index.md
#   - GCP: ./courses/gcp/index.md
#   - CI/CD: ./courses/cicd/index.md
#   - Monitoring: ./courses/monitoring/index.md
  - Data Science:
      - ./courses/datascience/index.md
      - Introduction: ./courses/datascience/01-introduction/index.md
      - NumPy: 
        - ./courses/datascience/05-numpy/index.md
        - Introduction : ./courses/datascience/05-numpy/01_numpy_introduction.md
        - Introductionv2 : ./courses/datascience/05-numpy/numpy.md
        - Arrays : ./courses/datascience/05-numpy/02_numpy_arrays.md
        - Indexing Slicing : ./courses/datascience/05-numpy/03_numpy_indexing_slicing.md
        - Broadcasting : ./courses/datascience/05-numpy/04_numpy_broadcasting.md
        - Vectorization : ./courses/datascience/05-numpy/05_numpy_vectorization.md
        - Math Statistics : ./courses/datascience/05-numpy/06_numpy_math_statistics.md
        - Linear Algebra : ./courses/datascience/05-numpy/07_numpy_linear_algebra.md
        - Random Module : ./courses/datascience/05-numpy/08_numpy_random_module.md
        - Memory Optimization : ./courses/datascience/05-numpy/09_numpy_memory_optimization.md
        - Performance Tips : ./courses/datascience/05-numpy/10_numpy_performance_tips.md
        - Cheatsheet : ./courses/datascience/05-numpy/11-numpy_interview_cheatsheet.md

#   - MLOps:
#       - Overview: ./courses/mlops/index.md
#       - Setup: ./courses/mlops/01-setup/index.md
#       - Data: ./courses/mlops/02-data/index.md
#       - Source Code: ./courses/mlops/03-src/index.md
#       - Notebooks: ./courses/mlops/04-notebooks/index.md
#       - DVC: ./courses/mlops/05-dvc/index.md
#       - Experiments: ./courses/mlops/06-experiments/index.md
#       - Serving: ./courses/mlops/07-serving/index.md
#       - Tests: ./courses/mlops/08-tests/index.md
#       - CI/CD: ./courses/mlops/09-ci-cd/index.md
#       - Kubernetes Deployment: ./courses/mlops/10-k8s/index.md
#       - Kubeflow: ./courses/mlops/11-kubeflow/index.md
#       - GitOps: ./courses/mlops/12-gitops/index.md
#       - Monitoring: ./courses/mlops/13-monitoring/index.md
#       - Model Monitoring: ./courses/mlops/14-monitoring-ml/index.md
#       - Feature Store: ./courses/mlops/15-feature-store/index.md
#       - Terraform: ./courses/mlops/16-terraform/index.md
#       - Projects: ./courses/mlops/17-projects/index.md
 
#   - Lab Setup: ./lab-setup/index.md
#   - Cheat Sheet: ./courses/cheatsheet/index.md
#   - Interview Q&A: ./courses/interviewqna/index.md  
  - Projects:
      - ./courses/projects/index.md
      - Nextcloud: ./courses/projects/nextcloud/index.md